name: system_clock
description: Dart timekeeping facilities. Make it easy to get uptime, and elapsed time.
version: 3.0.0
homepage: https://github.com/boyan01/system_clock

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
  ffigen: ^7.2.0
